In [1]:
import pandas as pd

In [6]:
df = pd.read_csv(r'C:\Users\DYPEF\Desktop\dsbdall\HospInfo.csv\HospInfo.csv')

In [7]:
df

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote,Location
0,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN,"2505 U S HIGHWAY 431 NORTH\nBOAZ, AL\n"
1,10012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DE KALB,2568453150,Acute Care Hospitals,Proprietary,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN,"200 MED CENTER DRIVE\nFORT PAYNE, AL\n"
2,10032,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,36278,RANDOLPH,2563572111,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"209 NORTH MAIN STREET\nWEDOWEE, AL\n"
3,10095,HALE COUNTY HOSPITAL,508 GREEN STREET,GREENSBORO,AL,36744,HALE,3346243024,Acute Care Hospitals,Government - Local,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Below the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"508 GREEN STREET\nGREENSBORO, AL\n"
4,10131,CRESTWOOD MEDICAL CENTER,ONE HOSPITAL DR SE,HUNTSVILLE,AL,35801,MADISON,2568823100,Acute Care Hospitals,Proprietary,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,"ONE HOSPITAL DR SE\nHUNTSVILLE, AL\n"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,450617,CLEAR LAKE REGIONAL MEDICAL CENTER,500 MEDICAL CENTER BLVD,WEBSTER,TX,77598,HARRIS,2813322511,Acute Care Hospitals,Proprietary,...,NaN,Below the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,"500 MEDICAL CENTER BLVD\nWEBSTER, TX\n(29.5410..."
4808,520194,ORTHOPAEDIC HOSPITAL OF WISCONSIN,475 W RIVER WOODS PKWY,GLENDALE,WI,53212,MILWAUKEE,4149616800,Acute Care Hospitals,Voluntary non-profit - Other,...,Results are not available for this reporting p...,Above the national average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"475 W RIVER WOODS PKWY\nGLENDALE, WI\n(43.0982..."
4809,491302,CARILION GILES COMMUNITY HOSPITAL,159 HARTLEY WAY,PEARISBURG,VA,24134,GILES,5409216000,Critical Access Hospitals,Voluntary non-profit - Private,...,NaN,Above the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,"159 HARTLEY WAY\nPEARISBURG, VA\n(37.332697, -..."
4810,510012,PLEASANT VALLEY HOSPITAL,2520 VALLEY DRIVE,POINT PLEASANT,WV,25550,MASON,3046754340,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Same as the national average,NaN,Below the national average,NaN,Above the national average,NaN,Same as the national average,NaN,"2520 VALLEY DRIVE\nPOINT PLEASANT, WV\n(38.868..."
4811,490053,JOHNSTON MEMORIAL HOSPITAL,16000 JOHNSTON MEMORIAL DRIVE,ABINGDON,VA,24211,WASHINGTON,2762581000,Acute Care Hospitals,Voluntary non-profit - Private,...,NaN,Below the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,"16000 JOHNSTON MEMORIAL DRIVE\nABINGDON, VA\n(..."

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Data columns (total 29 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Provider ID                                                    4812 non-null   int64
 1   Hospital Name                                                  4812 non-null   object
 2   Address                                                        4812 non-null   object
 3   City                                                           4812 non-null   object
 4   State                                                          4812 non-null   object
 5   ZIP Code                                                       4812 non-null   int64
 6   County Name                                                    4797 non-null   object
 7   Phone Number                                                   4812 non-null   int64
 8   Hospital Type                                                  4812 non-null   object
 9   Hospital Ownership                                             4812 non-null   object
 10  Emergency Services                                             4812 non-null   bool
 11  Meets criteria for meaningful use of EHRs                      4668 non-null   object
 12  Hospital overall rating                                        4812 non-null   object
 13  Hospital overall rating footnote                               1398 non-null   object
 14  Mortality national comparison                                  4812 non-null   object
 15  Mortality national comparison footnote                         1352 non-null   object
 16  Safety of care national comparison                             4812 non-null   object
 17  Safety of care national comparison footnote                    2168 non-null   object
 18  Readmission national comparison                                4812 non-null   object
 19  Readmission national comparison footnote                       1017 non-null   object
 20  Patient experience national comparison                         4812 non-null   object
 21  Patient experience national comparison footnote                1369 non-null   object
 22  Effectiveness of care national comparison                      4812 non-null   object
 23  Effectiveness of care national comparison footnote             1202 non-null   object
 24  Timeliness of care national comparison                         4812 non-null   object
 25  Timeliness of care national comparison footnote                1266 non-null   object
 26  Efficient use of medical imaging national comparison           4812 non-null   object
 27  Efficient use of medical imaging national comparison footnote  2033 non-null   object
 28  Location                                                       4812 non-null   object
dtypes: bool(1), int64(3), object(25)
memory usage: 1.0+ MB

In [10]:
z=df[['Provider ID','ZIP Code', 'Phone Number', 'Emergency Services']]

In [14]:
df['Provider ID']

0        10005
1        10012
2        10032
3        10095
4        10131
         ...
4807    450617
4808    520194
4809    491302
4810    510012
4811    490053
Name: Provider ID, Length: 4812, dtype: int64

In [15]:
z

      Provider ID  ZIP Code  Phone Number  Emergency Services
0           10005     35957    2565938310                True
1           10012     35968    2568453150                True
2           10032     36278    2563572111                True
3           10095     36744    3346243024                True
4           10131     35801    2568823100                True
...           ...       ...           ...                 ...
4807       450617     77598    2813322511                True
4808       520194     53212    4149616800               False
4809       491302     24134    5409216000                True
4810       510012     25550    3046754340                True
4811       490053     24211    2762581000                True

[4812 rows x 4 columns]

In [16]:
df['Provider ID'].min()

10001

In [17]:
df['Provider ID'].max()

670118

In [18]:
df['Provider ID'].notnull()

0       True
1       True
2       True
3       True
4       True
        ...
4807    True
4808    True
4809    True
4810    True
4811    True
Name: Provider ID, Length: 4812, dtype: bool

In [19]:
x=pd.notnull(['Emergency Services'])

In [20]:
x

array([ True])

In [21]:
from sklearn import preprocessing

In [22]:
y=df.fillna(df['Provider ID'].min())

In [23]:
y

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote,Location
0,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,10001,Same as the national average,10001,Same as the national average,10001,Above the national average,10001,Below the national average,10001,"2505 U S HIGHWAY 431 NORTH\nBOAZ, AL\n"
1,10012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DE KALB,2568453150,Acute Care Hospitals,Proprietary,...,10001,Same as the national average,10001,Same as the national average,10001,Above the national average,10001,Same as the national average,10001,"200 MED CENTER DRIVE\nFORT PAYNE, AL\n"
2,10032,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,36278,RANDOLPH,2563572111,Acute Care Hospitals,Government - Hospital District or Authority,...,10001,Not Available,Results are not available for this reporting p...,Same as the national average,10001,Same as the national average,10001,Not Available,Results are not available for this reporting p...,"209 NORTH MAIN STREET\nWEDOWEE, AL\n"
3,10095,HALE COUNTY HOSPITAL,508 GREEN STREET,GREENSBORO,AL,36744,HALE,3346243024,Acute Care Hospitals,Government - Local,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Below the national average,10001,Same as the national average,10001,Not Available,Results are not available for this reporting p...,"508 GREEN STREET\nGREENSBORO, AL\n"
4,10131,CRESTWOOD MEDICAL CENTER,ONE HOSPITAL DR SE,HUNTSVILLE,AL,35801,MADISON,2568823100,Acute Care Hospitals,Proprietary,...,10001,Same as the national average,10001,Same as the national average,10001,Same as the national average,10001,Same as the national average,10001,"ONE HOSPITAL DR SE\nHUNTSVILLE, AL\n"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,450617,CLEAR LAKE REGIONAL MEDICAL CENTER,500 MEDICAL CENTER BLVD,WEBSTER,TX,77598,HARRIS,2813322511,Acute Care Hospitals,Proprietary,...,10001,Below the national average,10001,Same as the national average,10001,Same as the national average,10001,Same as the national average,10001,"500 MEDICAL CENTER BLVD\nWEBSTER, TX\n(29.5410..."
4808,520194,ORTHOPAEDIC HOSPITAL OF WISCONSIN,475 W RIVER WOODS PKWY,GLENDALE,WI,53212,MILWAUKEE,4149616800,Acute Care Hospitals,Voluntary non-profit - Other,...,Results are not available for this reporting p...,Above the national average,10001,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"475 W RIVER WOODS PKWY\nGLENDALE, WI\n(43.0982..."
4809,491302,CARILION GILES COMMUNITY HOSPITAL,159 HARTLEY WAY,PEARISBURG,VA,24134,GILES,5409216000,Critical Access Hospitals,Voluntary non-profit - Private,...,10001,Above the national average,10001,Same as the national average,10001,Same as the national average,10001,Same as the national average,10001,"159 HARTLEY WAY\nPEARISBURG, VA\n(37.332697, -..."
4810,510012,PLEASANT VALLEY HOSPITAL,2520 VALLEY DRIVE,POINT PLEASANT,WV,25550,MASON,3046754340,Acute Care Hospitals,Voluntary non-profit - Private,...,10001,Same as the national average,10001,Below the national average,10001,Above the national average,10001,Same as the national average,10001,"2520 VALLEY DRIVE\nPOINT PLEASANT, WV\n(38.868..."
4811,490053,JOHNSTON MEMORIAL HOSPITAL,16000 JOHNSTON MEMORIAL DRIVE,ABINGDON,VA,24211,WASHINGTON,2762581000,Acute Care Hospitals,Voluntary non-profit - Private,...,10001,Below the national average,10001,Same as the national average,10001,Same as the national average,10001,Above the national average,10001,"16000 JOHNSTON MEMORIAL DRIVE\nABINGDON, VA\n(..."

In [24]:
scaler = preprocessing.MinMaxScaler()

In [25]:
x=scaler.fit_transform(z)

In [26]:
x

array([[6.05953187e-06, 3.55939029e-01, 1.81767776e-01, 1.00000000e+00],
       [1.66637126e-05, 3.56049775e-01, 1.82048387e-01, 1.00000000e+00],
       [4.69613720e-05, 3.59170811e-01, 1.81503750e-01, 1.00000000e+00],
       ...,
       [7.29114687e-01, 2.36906752e-01, 4.99026734e-01, 1.00000000e+00],
       [7.57458148e-01, 2.51162838e-01, 2.35418248e-01, 1.00000000e+00],
       [7.27222598e-01, 2.37681977e-01, 2.03709584e-01, 1.00000000e+00]])

In [29]:
frame=pd.DataFrame(x, columns=['Provider ID','ZIP Code', 'Phone Number', 'Emergency Services'])

In [30]:
frame

      Provider ID  ZIP Code  Phone Number  Emergency Services
0        0.000006  0.355939      0.181768                 1.0
1        0.000017  0.356050      0.182048                 1.0
2        0.000047  0.359171      0.181504                 1.0
3        0.000142  0.363862      0.268836                 1.0
4        0.000197  0.354368      0.182090                 1.0
...           ...       ...           ...                 ...
4807     0.667482  0.775175      0.209371                 1.0
4808     0.772883  0.529660      0.358478                 0.0
4809     0.729115  0.236907      0.499027                 1.0
4810     0.757458  0.251163      0.235418                 1.0
4811     0.727223  0.237682      0.203710                 1.0

[4812 rows x 4 columns]